import { dockerManager } from './docker-manager';
import { gitOperations, GitConfig } from './git-operations';
import { claudeProfiles } from './profiles/claude';
import { openaiProfiles } from './profiles/openai';
import { githubCopilotProfiles } from './profiles/github-copilot';
import { ExecutorProfile } from './profiles/claude';

export interface ExecutionContext {
  workspaceId: string;
  issueId: string;
  issueKey: string;
  issueTitle: string;
  issueDescription: string;
  projectId: string;
  repositoryPath?: string;
  executorProfile: string;
  executorVariant?: string;
  initialPrompt?: string;
}

export interface ExecutionResult {
  success: boolean;
  containerId?: string;
  branchName?: string;
  commitSha?: string;
  error?: string;
  logs: string[];
}

export class AgentExecutor {
  private logs: string[] = [];
  private allProfiles: ExecutorProfile[];

  constructor() {
    this.allProfiles = [...claudeProfiles, ...openaiProfiles, ...githubCopilotProfiles];
  }

  async execute(context: ExecutionContext): Promise<ExecutionResult> {
    this.logs = [];
    this.log(`[Executor] Starting execution for issue: ${context.issueKey}`);

    try {
      // Step 1: Get executor profile
      const profile = this.getProfile(context.executorProfile, context.executorVariant);
      if (!profile) {
        throw new Error(`Executor profile not found: ${context.executorProfile}`);
      }
      this.log(`[Executor] Using profile: ${profile.displayName}`);

      // Step 2: Create Docker container
      this.log('[Executor] Creating Docker container...');
      const container = await dockerManager.createContainer({
        workspaceId: context.workspaceId,
        projectId: context.projectId,
        issueId: context.issueId,
        repositoryPath: context.repositoryPath,
        environmentVariables: profile.envVars,
      });
      this.log(`[Executor] Container created: ${container.id}`);

      // Step 3: Setup Git branch
      let branchName: string | undefined;
      if (context.repositoryPath) {
        branchName = `agent/${context.issueKey.toLowerCase()}`;
        this.log(`[Executor] Creating Git branch: ${branchName}`);

        const gitConfig: GitConfig = {
          repositoryPath: context.repositoryPath,
          branchName,
          userEmail: 'agent@tasknebula.io',
          userName: `TaskNebula Agent (${profile.executor})`,
        };

        await gitOperations.createBranch(gitConfig);
        this.log('[Executor] Git branch created');
      }

      // Step 4: Build agent command
      const command = this.buildCommand(profile, context);
      this.log(`[Executor] Executing command: ${command.join(' ')}`);

      // Step 5: Execute agent
      const result = await dockerManager.executeCommand(container, command, (log) => {
        this.log(log);
      });

      if (result.exitCode !== 0) {
        throw new Error(`Agent execution failed with exit code ${result.exitCode}: ${result.stderr}`);
      }

      this.log('[Executor] Agent execution completed successfully');

      // Step 6: Commit changes (if repository exists)
      let commitSha: string | undefined;
      if (context.repositoryPath && branchName) {
        const changedFiles = await gitOperations.getChangedFiles(context.repositoryPath);

        if (changedFiles.length > 0) {
          this.log(`[Executor] Committing ${changedFiles.length} changed files`);

          const gitConfig: GitConfig = {
            repositoryPath: context.repositoryPath,
            branchName,
            userEmail: 'agent@tasknebula.io',
            userName: `TaskNebula Agent (${profile.executor})`,
          };

          const commitMessage = `${context.issueKey}: ${context.issueTitle}\n\nGenerated by ${profile.displayName}\n\nCo-Authored-By: TaskNebula Agent <agent@tasknebula.io>`;

          const commitResult = await gitOperations.commitChanges(gitConfig, commitMessage);
          commitSha = commitResult.sha;
          this.log(`[Executor] Changes committed: ${commitSha}`);

          // Push to remote
          await gitOperations.pushBranch(gitConfig);
          this.log('[Executor] Changes pushed to remote');
        } else {
          this.log('[Executor] No changes to commit');
        }
      }

      // Step 7: Cleanup (keep container for debugging)
      this.log('[Executor] Execution completed successfully');

      return {
        success: true,
        containerId: container.id,
        branchName,
        commitSha,
        logs: this.logs,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.log(`[Executor] Execution failed: ${errorMessage}`);

      return {
        success: false,
        error: errorMessage,
        logs: this.logs,
      };
    }
  }

  async cleanup(workspaceId: string): Promise<void> {
    try {
      this.log(`[Executor] Cleaning up workspace: ${workspaceId}`);

      const container = await dockerManager.getContainerByWorkspace(workspaceId);
      if (container) {
        await dockerManager.stopContainer(container);
        await dockerManager.removeContainer(container);
        this.log('[Executor] Container removed');
      }
    } catch (error) {
      this.log(`[Executor] Cleanup failed: ${error instanceof Error ? error.message : 'Unknown'}`);
    }
  }

  private getProfile(executor: string, variant?: string): ExecutorProfile | undefined {
    return this.allProfiles.find(
      (p) => p.executor === executor && p.variant === (variant || 'DEFAULT')
    );
  }

  private buildCommand(profile: ExecutorProfile, context: ExecutionContext): string[] {
    const command = [profile.baseCommand, ...profile.extraParams];

    // Add initial prompt if provided
    const prompt = context.initialPrompt || this.buildDefaultPrompt(context);

    // Inject prompt as stdin or argument (depends on agent)
    if (profile.executor === 'CLAUDE_CODE') {
      command.push('--prompt', prompt);
    } else if (profile.executor === 'OPENAI') {
      command.push('--input', prompt);
    } else if (profile.executor === 'GITHUB_COPILOT') {
      command.push('--description', prompt);
    }

    return command;
  }

  private buildDefaultPrompt(context: ExecutionContext): string {
    return `Task: ${context.issueTitle}

Description:
${context.issueDescription || 'No description provided'}

Please implement this task following best practices. Focus on:
1. Clean, maintainable code
2. Proper error handling
3. Type safety (if applicable)
4. Tests (if applicable)
5. Documentation

Issue: ${context.issueKey}`;
  }

  private log(message: string): void {
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] ${message}`;
    this.logs.push(logEntry);
    console.log(logEntry);
  }

  getAllProfiles(): ExecutorProfile[] {
    return this.allProfiles;
  }

  getProfilesByExecutor(executor: string): ExecutorProfile[] {
    return this.allProfiles.filter((p) => p.executor === executor);
  }
}

export const agentExecutor = new AgentExecutor();
